version: '3.2'

volumes:
  data:
  portainer:

services:

  #LRR demo, bound to lrr.tvc-16.science
  lrr-demo:
    image: "difegue/lanraragi:latest"
    container_name: "lanraragi"
    ports:
     - "127.0.0.1:3000:3000"
    restart: always
    volumes:
     - type: bind
       source: /root/lanraragi
       target: /home/koyomi/lanraragi/content

  #TT-RSS DB
  ttrssdb:
    image: "postgres:alpine"
    container_name: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: pgpass
      PGDATA: /data
    volumes:
     - data:/data

  #Personal TT-RSS, bound to ttrss.tvc-16
  ttrss:
    image: "clue/ttrss"
    container_name: "tt-rss"
    restart: always
    ports:
     - "127.0.0.1:8000:80"
    depends_on:
     - ttrssdb
    links:
     - ttrssdb 
    environment:
     - DB_ENV_USER=postgres
     - DB_ENV_PASS=pgpass
     - DB_PORT=5432
     - DB_TYPE=pgsql
     - DB_HOST=ttrssdb

  #DoujinSoft, crudely wrapped in a tomcat container with bind duct tape
  doujinsoft:
    image: "tomcat:latest"
    container_name: "doujinsoft"
    restart: always
    ports:
     - "127.0.0.1:8080:8080"
    volumes:
     - type: bind
       source: /root/doujinsoft/webapps
       target: /usr/local/tomcat/webapps  
     - type: bind
       source: /root/doujinsoft/context.xml
       target: /usr/local/tomcat/conf/context.xml 
     - type: bind
       source: /root/doujinsoft/data
       target: /home/doujinsoft 

  #Portainer for remote management
  portainer:
    image: "portainer/portainer"
    container_name: "portainer"
    restart: always
    ports:
     - "127.0.0.1:9000:9000"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: portainer
        target: /data

  