name: Node CI

on:
  schedule:
  - cron: 0 9 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: NPM install
      run: |
        npm install
    - name: Epic lcl hack
      env:
        LCL_ID: ${{ secrets.LCL_ID }}
        LCL_CODE: ${{ secrets.LCL_CODE }}
      run: |
        node lclscraper.js  
    - name: Push pebble timeline pin
      env:
        TIMELINE_TOKEN: ${{ secrets.TIMELINE_TOKEN }}
      run: | 
        LAB1=$(cat lcl.json | jq -r '.[0].label')
        TOT1=$(cat lcl.json | jq -r '.[0].total')
        CODE1=$(cat lcl.json | jq -r '.[0].code')
        DATE=$(date +%s | jq 'todate')
        UUID=$(cat /proc/sys/kernel/random/uuid)
        TIMELINE_JSON="{\"id\": \"$UUID\",\"time\": $DATE,\"layout\": {\"type\": \"genericPin\",\"title\": \"$LAB1\",\"body\": \"$CODE1\",\"subtitle\": \"$TOT1 €\",\"tinyIcon\": \"system://images/STOCKS_EVENT\"}}"
        echo $TIMELINE_JSON
        curl -X PUT https://timeline-api.rebble.io/v1/user/pins/$UUID --header "Content-Type: application/json" --header "X-User-Token: $TIMELINE_TOKEN" -d "$TIMELINE_JSON"
